# Generated by Django 5.2.7 on 2025-10-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_artworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('artist', 'Artist')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
