# Generated by Django 5.2.7 on 2025-10-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_user_register_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='user_type',
        ),
    ]
