# Generated by Django 5.2.7 on 2025-10-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_remove_user_register_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='craftworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phn_no', models.IntegerField()),
                ('address', models.TextField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
