# Generated by Django 5.2.7 on 2025-11-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0006_artproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artproduct',
            old_name='artist',
            new_name='artistname',
        ),
    ]
