# Generated by Django 5.2.7 on 2025-11-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0007_rename_artist_artproduct_artistname'),
    ]

    operations = [
        migrations.CreateModel(
            name='craftproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('artistname', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
