# Generated by Django 5.2.7 on 2025-11-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0008_craftproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(null=True)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.artproduct')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.user_register')),
            ],
        ),
    ]
