# Generated by Django 5.2.7 on 2025-11-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_price', models.IntegerField(null=True)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.artproduct')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.user_register')),
            ],
        ),
    ]
