# Generated by Django 5.2.7 on 2025-11-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0010_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('on the way', 'on the way'), ('deliverd', 'deliverd'), ('cancelled', 'cancelled'), ('returned', 'returned')], default='on the way', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.user_register')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app3.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.artproduct')),
            ],
        ),
    ]
