# Generated by Django 5.2.7 on 2025-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproduct',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
