# Generated by Django 5.2.6 on 2025-11-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0012_alter_artproduct_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_details',
        ),
        migrations.AddField(
            model_name='cart',
            name='art_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.artproduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='craft_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.craftproduct'),
        ),
    ]
