# Generated by Django 5.2.6 on 2025-11-19 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0013_remove_cart_product_details_cart_art_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_details',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='art_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.artproduct'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='craft_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.craftproduct'),
        ),
    ]
