# Generated by Django 5.2.7 on 2025-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
