# Generated by Django 5.2.6 on 2025-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0020_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworker',
            name='id_proof',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craftworker',
            name='id_proof',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
