# Generated by Django 5.2.6 on 2025-12-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0021_artworker_id_proof_craftworker_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
