# Generated by Django 5.2.6 on 2025-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0022_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
